export var scriptures = [
  "Acts 17:28 - In Him we live and move and have our being.",
  "Romans 3:24 - Being justified freely by His grace through the redemption that is in Christ Jesus.",
  "Romans 8:1 - There is therefore now no condemnation to those who are in Christ Jesus.",
  "Romans 8:2 - For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
  "Romans 12:5 - So we, being many, are one body in Christ, and every one members one of another.",
  "Romans 6:11 - Likewise reckon ye also yourselves to be dead indeed unto sin, but alive unto God through Jesus Christ our Lord.",
  "1 Corinthians 1:2 - To them that are sanctified in Christ Jesus, called to be saints...",
  "1 Corinthians 1:30 - But of Him are ye in Christ Jesus, who of God is made unto us wisdom, and righteousness, and sanctification, and redemption.",
  "1 Corinthians 15:22 - For as in Adam all die, even so in Christ shall all be made alive.",
  "2 Corinthians 1:21 - Now He which stablisheth us with you in Christ, and hath anointed us, is God.",
  "2 Corinthians 2:14 - Now thanks be unto God, which always causeth us to triumph in Christ, and maketh manifest the savour of His knowledge by us in every place.",
  "2 Corinthians 3:14 - But their minds were blinded: for until this day remaineth the same vail untaken away in the reading of the old testament; which vail is done away in Christ.",
  "2 Corinthians 5:17 - Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
  "2 Corinthians 5:21 - For He hath made Him to be sin for us, who knew no sin; that we might be made the righteousness of God in Him.",
  "Galatians 2:4 - And that because of false brethren unawares brought in, who came in privily to spy out our liberty which we have in Christ Jesus, that they might bring us into bondage.",
  "Galatians 2:16 - Knowing that a man is not justified by the works of the law, but by the faith of Jesus Christ...",
  "Galatians 3:26 - For ye are all the children of God by faith in Christ Jesus.",
  "Galatians 3:28 - There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus.",
  "Galatians 5:6 - For in Jesus Christ neither circumcision availeth anything, nor uncircumcision; but faith which worketh by love.",
  "Ephesians 1:3 - Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ.",
  "Ephesians 1:4 - According as He hath chosen us in Him before the foundation of the world...",
  "Ephesians 1:7 - In whom we have redemption through His blood, the forgiveness of sins, according to the riches of His grace.",
  "Ephesians 1:10 - That in the dispensation of the fulness of times He might gather together in one all things in Christ...",
  "Ephesians 1:11 - In whom also we have obtained an inheritance, being predestinated according to the purpose of Him who worketh all things after the counsel of His own will.",
  "Ephesians 2:6 - And hath raised us up together, and made us sit together in heavenly places in Christ Jesus.",
  "Ephesians 2:7 - That in the ages to come He might show the exceeding riches of His grace in His kindness toward us through Christ Jesus.",
  "Ephesians 2:10 - For we are His workmanship, created in Christ Jesus unto good works...",
  "Ephesians 2:13 - But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.",
  "Ephesians 3:6 - That the Gentiles should be fellowheirs, and of the same body, and partakers of His promise in Christ by the gospel.",
  "Philippians 2:5 - Let this mind be in you, which was also in Christ Jesus.",
  "Philippians 3:9 - And be found in Him, not having mine own righteousness, which is of the law, but that which is through the faith of Christ...",
  "Philippians 4:7 - And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
  "Philippians 4:19 - But my God shall supply all your need according to His riches in glory by Christ Jesus.",
  "Colossians 1:14 - In whom we have redemption through His blood, even the forgiveness of sins.",
  "Colossians 1:16 - For by Him were all things created, that are in heaven, and that are in earth, visible and invisible...",
  "Colossians 1:17 - And He is before all things, and by Him all things consist.",
  "Colossians 2:6 - As ye have therefore received Christ Jesus the Lord, so walk ye in Him.",
  "Colossians 2:10 - And ye are complete in Him, which is the head of all principality and power.",
  "Colossians 2:11 - In whom also ye are circumcised with the circumcision made without hands...",
  "Colossians 3:3 - For ye are dead, and your life is hid with Christ in God.",
  "2 Timothy 1:9 - Who hath saved us, and called us with an holy calling, not according to our works, but according to His own purpose and grace, which was given us in Christ Jesus before the world began.",
  "2 Timothy 2:1 - Thou therefore, my son, be strong in the grace that is in Christ Jesus.",
  "2 Timothy 2:10 - Therefore I endure all things for the elect's sakes, that they may also obtain the salvation which is in Christ Jesus with eternal glory.",
  "2 Timothy 3:15 - And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus.",
  "Philemon 1:6 - That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus.",
  "1 Peter 5:10 - But the God of all grace, who hath called us unto His eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.",
];
